"""Initial schema

Revision ID: ae65b4b441ae
Revises: 
Create Date: 2026-03-23 15:53:39.039944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae65b4b441ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condutores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('resistencia_ohm_km', sa.Float(), nullable=False),
    sa.Column('ampacidade_a', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projetos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('localidade', sa.String(length=200), nullable=False),
    sa.Column('etapa_atual', sa.String(length=40), nullable=False),
    sa.Column('checklist_triagem', sa.JSON(), nullable=False),
    sa.Column('evidencias', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projetos_codigo'), 'projetos', ['codigo'], unique=True)
    op.create_table('cqt_analises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('projeto_id', sa.String(length=36), nullable=False),
    sa.Column('tipo_projeto', sa.String(length=40), nullable=False),
    sa.Column('recuperacao_clandestino_confirmada', sa.Boolean(), nullable=True),
    sa.Column('quantidade_ligacoes_irregulares', sa.Integer(), nullable=True),
    sa.Column('recebeu_leitura_trafo_maxima', sa.Boolean(), nullable=False),
    sa.Column('corrente_trafo_a', sa.Float(), nullable=True),
    sa.Column('carga_maxima_transformador_kva', sa.Float(), nullable=True),
    sa.Column('limite_carregamento_trafo_percent', sa.Float(), nullable=False),
    sa.Column('trafo_dentro_do_limite', sa.Boolean(), nullable=False),
    sa.Column('qdt_total_dentro_do_limite', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cqt_analises_projeto_id'), 'cqt_analises', ['projeto_id'], unique=False)
    op.create_table('geometrias_projeto',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('projeto_id', sa.String(length=36), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=260), nullable=False),
    sa.Column('versao_dxf', sa.String(length=20), nullable=False),
    sa.Column('dados_geometria', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id')
    )
    op.create_table('historico_auditoria',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('projeto_id', sa.String(length=36), nullable=False),
    sa.Column('etapa_origem', sa.String(length=40), nullable=True),
    sa.Column('etapa_destino', sa.String(length=40), nullable=False),
    sa.Column('acao', sa.String(length=200), nullable=False),
    sa.Column('responsavel', sa.String(length=120), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('ocorrido_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_auditoria_projeto_id'), 'historico_auditoria', ['projeto_id'], unique=False)
    op.create_table('pacotes_entrega',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('projeto_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=True),
    sa.Column('arquivos_contidos', sa.JSON(), nullable=False),
    sa.Column('mensagem_erro', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacotes_entrega_projeto_id'), 'pacotes_entrega', ['projeto_id'], unique=True)
    op.create_table('postes_tracao',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('projeto_id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('resistencia_nominal_daN', sa.Float(), nullable=False),
    sa.Column('vaos_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postes_tracao_projeto_id'), 'postes_tracao', ['projeto_id'], unique=False)
    op.create_table('centros_carga',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cqt_analise_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('queda_total_percent', sa.Float(), nullable=False),
    sa.Column('possui_erro_02', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cqt_analise_id'], ['cqt_analises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cqt_analise_id')
    )
    op.create_table('resultados_tracao',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('poste_id', sa.String(length=36), nullable=False),
    sa.Column('esforco_resultante_daN', sa.Float(), nullable=False),
    sa.Column('percentual_carregamento', sa.Float(), nullable=False),
    sa.Column('estado_mecanico', sa.String(length=20), nullable=False),
    sa.Column('calculado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['poste_id'], ['postes_tracao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resultados_tracao_poste_id'), 'resultados_tracao', ['poste_id'], unique=True)
    op.create_table('transformadores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('centro_carga_id', sa.String(length=36), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('potencia_nominal_kva', sa.Float(), nullable=False),
    sa.Column('carga_maxima_lida_kva', sa.Float(), nullable=False),
    sa.Column('corrente_lida_a', sa.Float(), nullable=True),
    sa.Column('fator_carga_percent', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['centro_carga_id'], ['centros_carga.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('centro_carga_id')
    )
    op.create_table('trechos_eletricos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('centro_carga_id', sa.String(length=36), nullable=False),
    sa.Column('condutor_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo_rede', sa.String(length=20), nullable=False),
    sa.Column('fases', sa.Integer(), nullable=False),
    sa.Column('comprimento_m', sa.Float(), nullable=False),
    sa.Column('corrente_a', sa.Float(), nullable=False),
    sa.Column('tensao_nominal_v', sa.Float(), nullable=False),
    sa.Column('ordem_no_circuito', sa.Integer(), nullable=False),
    sa.Column('consumidores_montante', sa.Integer(), nullable=True),
    sa.Column('consumidores_jusante', sa.Integer(), nullable=True),
    sa.Column('fases_montante', sa.Integer(), nullable=True),
    sa.Column('fases_jusante', sa.Integer(), nullable=True),
    sa.Column('resistencia_total_ohm', sa.Float(), nullable=False),
    sa.Column('queda_tensao_v', sa.Float(), nullable=False),
    sa.Column('queda_tensao_percent', sa.Float(), nullable=False),
    sa.Column('limite_qdt_percent', sa.Float(), nullable=False),
    sa.Column('dentro_do_limite_qdt', sa.Boolean(), nullable=False),
    sa.Column('possui_erro_02', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['centro_carga_id'], ['centros_carga.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['condutor_id'], ['condutores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trechos_eletricos_centro_carga_id'), 'trechos_eletricos', ['centro_carga_id'], unique=False)
    op.create_index(op.f('ix_trechos_eletricos_condutor_id'), 'trechos_eletricos', ['condutor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trechos_eletricos_condutor_id'), table_name='trechos_eletricos')
    op.drop_index(op.f('ix_trechos_eletricos_centro_carga_id'), table_name='trechos_eletricos')
    op.drop_table('trechos_eletricos')
    op.drop_table('transformadores')
    op.drop_index(op.f('ix_resultados_tracao_poste_id'), table_name='resultados_tracao')
    op.drop_table('resultados_tracao')
    op.drop_table('centros_carga')
    op.drop_index(op.f('ix_postes_tracao_projeto_id'), table_name='postes_tracao')
    op.drop_table('postes_tracao')
    op.drop_index(op.f('ix_pacotes_entrega_projeto_id'), table_name='pacotes_entrega')
    op.drop_table('pacotes_entrega')
    op.drop_index(op.f('ix_historico_auditoria_projeto_id'), table_name='historico_auditoria')
    op.drop_table('historico_auditoria')
    op.drop_table('geometrias_projeto')
    op.drop_index(op.f('ix_cqt_analises_projeto_id'), table_name='cqt_analises')
    op.drop_table('cqt_analises')
    op.drop_index(op.f('ix_projetos_codigo'), table_name='projetos')
    op.drop_table('projetos')
    op.drop_table('condutores')
    # ### end Alembic commands ###
